[package]
name = "kernel-updated"
version = "0.1.1"
authors = [
  "Raphael Nestler <raphael.nestler@gmail.com>",
  "Stefan Schindler <stefan@estada.ch>",
]

[dependencies]
notify-rust = "3.0"
docopt = "1.1"
serde = "1.0"
serde_derive = "1.0"
